window.PMX_CONFIG = Object.freeze({
  gameId: "PMX-WS-2026-W01",
  gameLabel: "SEASON OPENER",
  kickerMobile: "SEASON OPENER",
  kickerDesktop: "SEASON OPENER",
  week: "WEEK 1",
  opponent: "VIKINGS",
  opponentLong: "Minnesota Vikings",
  homeAway: "AWAY",
  date: "DOM 13 SEP",
  time: "14:25",
  timezone: "America/Mexico_City",
  venue: "Wingstop Condesa",
  venueWording: "Casa Oficial de Packers en CDMX",
  registrationUrl: "https://share.forms.app/form/6a96032ee64cd5f15d1688aa",
  mapsUrl: "https://www.google.com/maps/search/?api=1&query=Wingstop%20Condesa&query_place_id=ChIJ8WFFePj_0YURO5krqxenfu8",
  heroImageUrl: "",
  dataPending: true,
  promoEnabled: false,
  promoTitle: "",
  promoDescription: "",
  promoUrl: "",
  specialEnabled: false,
  specialTitle: "",
  specialDescription: "",
  calendarUrl: "https://packersmexico.github.io/calendario/",
  gopackgoUrl: "https://youtu.be/BZBuRy3LHUY",
  quiniela: Object.freeze({
    enabled: true,
    week: "WEEK 1",
    label: "QUINIELA · WEEK 1",
    title: "TODOS LOS PICKS",
    meta: "9 integrantes · 16 partidos · 144 selecciones",
    description: "Consulta la selección completa del board y revisa los picks de cada integrante.",
    url: "https://packersmexico.github.io/quiniela/w01/",
    members: Object.freeze([
      "EL DOC",
      "ARI",
      "LALO",
      "ALEX",
      "LUIS C.",
      "DR PALMA",
      "JENNI",
      "RODRI",
      "IBRACHO"
    ])
  }),
  analytics: Object.freeze({
    GA4_MEASUREMENT_ID: "G-QEN5F5YY14",
    hubVersion: "p0",
    eventVersion: "1.1"
  }),
  socialUrls: Object.freeze({
    facebook: "https://www.facebook.com/gopackgomx/",
    instagram: "https://www.instagram.com/packers_mx/",
    x: "https://x.com/Packers_Mx",
    tiktok: "https://www.tiktok.com/@packers_mx",
    youtube: "https://www.youtube.com/@gopackgomx6092"
  })
});
